### ISSUE TITLE
Why is viewing_angle in the renderer is set to 15?

### ISSUE THREAD

**Issue by sunshineatnoon** [hiroharu-kato/mesh_reconstruction#4]
Hi,

Thanks for open-sourcing this awesome project. I'm trying to implement the mesh reconstruction in Pytorch. So far I can get some decent results on the car category except the obvious artifacts shown below:
![](https://raw.githubusercontent.com/sunshineatnoon/Paper-Collection/master/%5B%22images%22%5D/Screenshot%20from%202019-06-13%2013-44-27.png)
![](https://raw.githubusercontent.com/sunshineatnoon/Paper-Collection/master/%5B%22images%22%5D/Screenshot%20from%202019-06-13%2013-44-37.png)

After some exploration, I found this seems to be relevant to the viewing_angle, which is set to 15 in the experiment. I am a newbie in 3D graphics, I would appreciate if you could shed some light on this parameter and possible reasons for the artifacts shown above.

**Comment by AlexsaseXie** [comment]
I guess the viewing_angle is similar to fovy in gluPerspective though i didn't go through all code in the neural_renderer...

**Comment by sunshineatnoon** [comment]
I found the issue, it's because of the global bias. Without using the global bias, the reconstructions look reasonable.

**Comment by bharadwajdhornala** [comment]
Hi @sunshineatnoon @AlexsaseXie Can you help me with #6
